search_parameters:
  positions: []
  locations: []
  distance: null
  remote: true
  candidate_experience_years: 0
  candidate_skills: []
  jobTypes:
    full_time: false
    contract: false
  experienceLevel:
    mid_level: false
    senior: false
  date_range:
    past_24_hours: false
  apply_once_at_company: true
  companyBlacklist: []
  titleBlacklist: []
  target_portals:
    linkedin: true
    instahyre: true
    cutshort: true
    wellfound: true
    hirist: true
    naukri: true
    indeed: true
    foundit: true
    shine: true
    timesjobs: true
    glassdoor: true
candidate_identity:
  personal_details:
    first_name: ""
    last_name: ""
    email: ""
    phone: ""
  demographics:
    gender: ""
    pronouns: ""
    veteran_status: ""
    disability_status: ""
    ethnicity: ""
compliance_preferences:
  remote_work: ""
  in_person_work: ""
  open_to_relocation: ""
  relocation_destinations: ""
  willing_to_complete_assessments: ""
  willing_to_undergo_drug_tests: ""
  willing_to_undergo_background_checks: ""
