services:
  - type: web
    name: job-application-system
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8000"
      - key: MONGODB_URI
        sync: false
